# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'P04_SumaDosNumeros.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(763, 552)
        MainWindow.setStyleSheet("background-color: rgb(85, 170, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_sumar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_sumar.setGeometry(QtCore.QRect(230, 330, 331, 121))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_sumar.setFont(font)
        self.btn_sumar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_sumar.setStyleSheet("background-color: rgb(170, 85, 255);\n"
"background-color: rgb(255, 170, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 25px;\n"
"border:  5px solid black;")
        self.btn_sumar.setObjectName("btn_sumar")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(290, -10, 201, 51))
        self.label.setObjectName("label")
        self.txt_A = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_A.setGeometry(QtCore.QRect(280, 40, 211, 71))
        self.txt_A.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.txt_A.setStyleSheet("background-color: rgb(85, 170, 255);\n"
"border-radius:20px;\n"
"border:  5px solid black;")
        self.txt_A.setText("")
        self.txt_A.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_A.setObjectName("txt_A")
        self.txt_B = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_B.setGeometry(QtCore.QRect(280, 230, 211, 71))
        self.txt_B.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.txt_B.setStyleSheet("background-color: rgb(85, 170, 255);\n"
"border-radius:20px;\n"
"border:  5px solid black;")
        self.txt_B.setText("")
        self.txt_B.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_B.setObjectName("txt_B")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(280, 180, 221, 51))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(330, 120, 111, 61))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_3.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.btn_sumar.raise_()
        self.txt_A.raise_()
        self.txt_B.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 763, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_sumar.setText(_translate("MainWindow", "S U M A R"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">PRIMER NUMERO:</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">SEGUNDO NUMERO:</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:26pt; font-weight:600;\">+</span></p></body></html>"))
