# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'P08_PromedioNumeros_Load_V2.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(808, 457)
        MainWindow.setStyleSheet("background-color: rgb(85, 170, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_agregar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_agregar.setGeometry(QtCore.QRect(20, 150, 301, 81))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_agregar.setFont(font)
        self.btn_agregar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_agregar.setStyleSheet("background-color: rgb(170, 85, 255);\n"
"background-color: rgb(255, 170, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 25px;\n"
"border:  5px solid black;")
        self.btn_agregar.setObjectName("btn_agregar")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 201, 51))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.txt_calificacion = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_calificacion.setGeometry(QtCore.QRect(20, 60, 211, 71))
        self.txt_calificacion.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.txt_calificacion.setStyleSheet("background-color: rgb(85, 170, 255);\n"
"border-radius:20px;\n"
"border:  5px solid black;")
        self.txt_calificacion.setText("")
        self.txt_calificacion.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_calificacion.setObjectName("txt_calificacion")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(240, 10, 221, 51))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.txt_promedio = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_promedio.setGeometry(QtCore.QRect(250, 60, 211, 71))
        self.txt_promedio.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.txt_promedio.setStyleSheet("background-color: rgb(85, 170, 255);\n"
"border-radius:20px;\n"
"border:  5px solid black;")
        self.txt_promedio.setText("")
        self.txt_promedio.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_promedio.setObjectName("txt_promedio")
        self.btn_guardar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_guardar.setGeometry(QtCore.QRect(20, 240, 301, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_guardar.setFont(font)
        self.btn_guardar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_guardar.setStyleSheet("background-color: rgb(170, 85, 255);\n"
"background-color: rgb(255, 170, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 25px;\n"
"border:  5px solid black;")
        self.btn_guardar.setObjectName("btn_guardar")
        self.btn_cargar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_cargar.setGeometry(QtCore.QRect(410, 210, 281, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_cargar.setFont(font)
        self.btn_cargar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_cargar.setStyleSheet("background-color: rgb(170, 85, 255);\n"
"background-color: rgb(255, 170, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 25px;\n"
"border:  5px solid black;")
        self.btn_cargar.setObjectName("btn_cargar")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(510, 0, 201, 51))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.txt_linea_calificaciones = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_linea_calificaciones.setGeometry(QtCore.QRect(510, 60, 191, 131))
        self.txt_linea_calificaciones.setStyleSheet("background-color: rgb(85, 170, 255);\n"
"border-radius:20px;\n"
"border:  5px solid black;")
        self.txt_linea_calificaciones.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_linea_calificaciones.setObjectName("txt_linea_calificaciones")
        self.label.raise_()
        self.btn_agregar.raise_()
        self.txt_calificacion.raise_()
        self.label_4.raise_()
        self.txt_promedio.raise_()
        self.btn_guardar.raise_()
        self.btn_cargar.raise_()
        self.label_2.raise_()
        self.txt_linea_calificaciones.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 808, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_agregar.setText(_translate("MainWindow", "A G R E G A R"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Calificacion:</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Resultado:</span></p></body></html>"))
        self.btn_guardar.setText(_translate("MainWindow", "G U A R D A R"))
        self.btn_cargar.setText(_translate("MainWindow", "C A R G A R"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Calificaciones:</span></p></body></html>"))
