# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'P2_Ejemplo.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1093, 784)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.imagen_2 = QtWidgets.QLabel(self.centralwidget)
        self.imagen_2.setGeometry(QtCore.QRect(290, 0, 191, 161))
        self.imagen_2.setStyleSheet("")
        self.imagen_2.setText("")
        self.imagen_2.setPixmap(QtGui.QPixmap(":/ejercicios/kaldo.jpg"))
        self.imagen_2.setScaledContents(True)
        self.imagen_2.setObjectName("imagen_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(70, 490, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.txt_numero1 = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_numero1.setGeometry(QtCore.QRect(310, 380, 151, 61))
        self.txt_numero1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_numero1.setObjectName("txt_numero1")
        self.btn_suma = QtWidgets.QPushButton(self.centralwidget)
        self.btn_suma.setGeometry(QtCore.QRect(320, 660, 93, 28))
        self.btn_suma.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btn_suma.setObjectName("btn_suma")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 380, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(620, -20, 421, 341))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap(":/ejercicios/samsgoku.jpeg"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.imagen = QtWidgets.QLabel(self.centralwidget)
        self.imagen.setGeometry(QtCore.QRect(20, -10, 191, 161))
        self.imagen.setStyleSheet("")
        self.imagen.setText("")
        self.imagen.setPixmap(QtGui.QPixmap(":/ejercicios/elyochi.jpg"))
        self.imagen.setScaledContents(True)
        self.imagen.setObjectName("imagen")
        self.txt_numero2 = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_numero2.setGeometry(QtCore.QRect(310, 480, 151, 61))
        self.txt_numero2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_numero2.setObjectName("txt_numero2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(70, 580, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.txt_numero3 = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_numero3.setGeometry(QtCore.QRect(310, 580, 151, 61))
        self.txt_numero3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_numero3.setObjectName("txt_numero3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1093, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)





        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "NUMERO 2"))
        self.btn_suma.setText(_translate("MainWindow", "SUMA"))
        self.label.setText(_translate("MainWindow", "NUMERO 1"))
        self.label_3.setText(_translate("MainWindow", "Numero 3"))
import Recursos_rc
